공연장 entity 구현
Ajou-Hertz/hertz-backend pull request #65
Opened 2024-03-01 23:27 UTC by tinon1004

## 🔥 Related Issue
- Close #62

## 🏃‍ Task
- 공연장 entity 구현

## 📄 Reference
- None

2024-03-02 05:43 UTC, Wo-ogie requested changes

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHallHashtags.java
> +	}
일급컬렉션을 사용하는 목적중 하나가 상태와 행위를 하나의 class에서 관리함으로써 내부 
데이터를 캡슐화하려는 부분도 있으니까, 지금 사용하지 않는 행위(method)라면 지워주시면 좋을 것 같아요.
나중에 business logic 구현하시면서 필요하시면 그때 추가해주시면 될 것 같습니다.

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +	private String detailAddress;
논의한대로 수정 부탁드립니다.

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +	private InstrumentProgressStatus progressStatus;
Enum class 잘못 참조하고 있는 것 같은데요?

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
"주차 가능 여부"를 저장할 필드가 안보이는 것 같습니다. 확인 부탁드려요!

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +	protected ConcertHall(
`ConvertHall`이 어디서 상속받을 class는 아니니까 `private`으로 두시면 될 거 같네요. `Instrument`는 `ElectricGuitar` 등의 하위 class에서 상속받아야 해서 `protected`로 둔겁니다.

2024-03-02 05:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHallImages.java
> +}
`ConcertHallHashtags`에서 작성한 리뷰와 동일 내용

2024-03-05 13:17 UTC, Wo-ogie requested changes

2024-03-05 13:17 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +
이건 혹시 왜 추가하신걸까요? 잘못 추가된 거 같습니다.

2024-03-06 00:45 UTC, Wo-ogie requested changes

2024-03-06 00:45 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +@Inheritance(strategy = InheritanceType.JOINED)
이건 잘못 붙인 거 같은데요? 이유가 있을까요?

2024-03-06 00:45 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +	private String detailAddress;
FullAddress 클래스에 있는 정보이니 지워주셔야 할 듯 보입니다.

2024-03-06 14:12 UTC, Wo-ogie requested changes

2024-03-06 14:12 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +@AllArgsConstructor
이것도 production 범위에서 필요한 만큼한 허용해주시면 좋을 것 같습니다.

2024-03-06 14:12 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
> +	private Integer capacity;
Type 자체를 Short로 선언하셔야 합니다.
Column definition은 이렇게 해도 동일한데, java 프로그램 상에서 small int 범위 바깥의 값이 담길 수 있게 되니까요.

2024-03-06 14:23 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +		String sgg = sggBuilder.toString().trim();
아하 시/군/구 정보를 building 하는 과정에서 공백이 들어가는군요.
혹시 그러면 `trim()`을 넣은 이유가 "수원시 영통구 "와 같은 경우가 발생하여 이를 "수원시 영통구"로 변경하고자 했다는 말씀이실까요?

2024-03-06 14:25 UTC, tinon1004 commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +		String sgg = sggBuilder.toString().trim();
네 맞습니다! 불필요한 코드 같다면 제거 하겠습니다

2024-03-06 14:28 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +		String sgg = sggBuilder.toString().trim();
아뇨 이해했습니다.
"수원시 영통구 "처럼 불필요한 공백이 있으면 안되는건 맞습니다.

2024-03-06 14:28 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +		String sgg = sggBuilder.toString().trim();
아뇨 이해했습니다.
"수원시 영통구 "처럼 불필요한 공백이 있으면 안되는건 맞습니다.

2024-03-11 12:07 UTC, Wo-ogie requested changes

2024-03-11 12:26 UTC, tinon1004 commented on src/main/java/com/ajou/hertz/common/entity/FullAddress.java
> +			.toArray().length + 1;
기존에 있던 for (i = 1; i < parsedAddress.length; i++) { 이 코드가 테스트 결과 노란색이었고, 이 코드때문에 테스트 검사에서 계속 실패되더라구요. 그래서  코드를 수정하다가 이 방법을 사용해서 테스트를 성공할 수 있었습니다. 익스트림을 사용한 특별한 이유는 따로 없습니다!

2024-03-11 13:43 UTC, Wo-ogie requested changes

2024-03-11 13:43 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/concert_hall/entity/ConcertHall.java
좌표(lat, lng) 정보 추가 필요합니다.

2024-03-11 16:04 UTC, Wo-ogie requested changes

2024-03-11 23:40 UTC, Wo-ogie approved these changes
수고하셨습니다!

2024-03-12 00:02 UTC, merged