내 연락수단 변경 API 구현
Ajou-Hertz/hertz-backend pull request #85
Opened 2024-03-16 05:15 UTC by tinon1004

## 🔥 Related Issue
- Close #72

## 🏃‍ Task
- 내 연락수단(contact-link)변경 API 구현

## 📄 Reference
- None

2024-03-16 07:33 UTC, Wo-ogie requested changes
이번주 목요일에 말씀드렸던 내용들 중 빠진 거 다시 달아두었습니다!

2024-03-16 07:33 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/entity/User.java
> +	}
이거 안쓰는 거 맞을까요? 맞으면 지워주세요.

2024-03-16 07:33 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +			.orElseThrow(() -> new UserNotFoundByIdException(userId));
여기 말씀드렸던대로 기존 코드 재사용하도록 바꿔주시면 좋을 거 같아요

2024-03-17 05:21 UTC, Wo-ogie requested changes

2024-03-17 05:21 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		)
이거 빼주세요

2024-03-17 05:21 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		return ResponseEntity.ok().build();
응답값이 없는 경우 200이 아닌 204로 return하시는게 좋습니다.
다만, 여기서는 목요일에 말씀드린것처럼 응답값을 담아서 200으로 응답하시는게 좋을 거 같아요. (ref. https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses)

2024-03-17 05:21 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/dto/request/UpdateContactLinkRequest.java
> +@AllArgsConstructor
이거 사용하는 곳 없으면 access modifier 수정해주세요

2024-03-17 05:21 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
> +		String contactLink = "https://contackLink";
`createUser`에서 생성 시 세팅하는 `contactLink`와 달라야 의미 있는 테스트가 될 거 같아요. 수정 필요해 보입니다.

2024-03-17 05:21 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
> +		String contactLink = "https://contackLink";
오타 수정해주세요

2024-03-17 05:21 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
> +			"https://contackLink"
오타 수정해주세요

2024-03-17 05:21 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerTest.java
> +
`UserCommandService.updateContactLink()`에 대한 mocking이 안되어 있네요. Action 정의 추가해주세요. (`given(...`)

2024-03-17 05:21 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerTest.java
> +		then(userCommandService).should().updateContactLink(eq(userId), eq(newContactLink));
`eq()` 안쓰셔도 됩니다.

2024-03-17 14:17 UTC, Wo-ogie requested changes

2024-03-17 14:17 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +	public ResponseEntity<UserContactLinkResponse> updateContactLinkV1(
`ResponseEntity`는 빼셔도 되고, `MemberResponse`를 사용하면 어떨까요?

2024-03-18 12:18 UTC, tinon1004 commented on src/main/java/com/ajou/hertz/domain/user/dto/request/UpdateContactLinkRequest.java
> +@AllArgsConstructor
이 부분은 사용되는 코드라 놔뒀습니다!

2024-03-18 23:48 UTC, Wo-ogie requested changes

2024-03-18 23:48 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		UserDto userDto = userQueryService.getDtoById(userPrincipal.getUserId());
여기 조회는 혹시 왜 하는 걸까요?
응답값도 딱히 안쓰는 거 같은데

2024-03-18 23:48 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
> +	}
응답값 변경되었으니 여기도 수정되면 좋을 거 같아요~

2024-03-18 23:48 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/dto/request/UpdateContactLinkRequest.java
> +@AllArgsConstructor
혹시 어디서 사용할까요?
일단... 이 PR에서만 봤을 때는 사용하는 곳이 테스트 코드 말고 안보이긴 한데, 혹시 제가 못본거라면 알려주세요! 😊
만약 테스트 코드에서만 사용하는 거라면 논의한 대로 reflection 사용하여 생성해주시면 될 거 같습니다.

2024-03-19 15:04 UTC, Wo-ogie requested changes

2024-03-19 15:04 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +	}
API consumer(API 호출한 유저)와 정보를 수정하고자 하는 user가 동일인인지 검증해주시면 좋을 거 같아요.
만약, 아니라면 403 FORBIDDEN response 던져주시면 될 거 같습니다.
물론 이에 대한 테스트 케이스도 추가해야겠죠?

2024-03-21 00:18 UTC, Wo-ogie requested changes

2024-03-21 00:18 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +		User user = userQueryService.getById(userId);
지금 controller 쪽 코드 보니까 `userCommandService.updateContactLink(userPrincipal.getUserId(), userPrincipal.getUserId(), updateContactLinkRequest.getContactLink());`로 되어 있던데, 이러면 비교하는 의미가 없지 않을까요? 무조건 `true`일 텐데요.

생각해보니까 어차피 들어오는 `userId`가 주체이자 타겟이니까 해당 검증은 빼도 될 거 같네요.
아무래도 제가 구현하는 기능이 아니라서 상대적으로 이해도가 떨어질 수 있어요. 작업하시다가 의아한 코멘트는 항상 의견 남겨주세요.

2024-03-21 01:51 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
> +	USER_ID_FORBIDDEN(2207, "해당 유저는 접근이 금지되었습니다."),
이것도 마저 지워주세요.
과거 작업을 살펴볼 땐 올렸던 git commit을 확인하면 꼼꼼하게 확인할 수 있어 좋습니다!

2024-03-21 01:53 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerTest.java
> +		given(userCommandService.updateContactLink(anyLong(), anyString())).willReturn(expectedResult);
`anyXxx()`를 쓰기보다는 아래 `then`에서 한 것처럼 실제 들어갈법한 값을 넣어 확인해주시면 좋을 거 같네요

2024-03-21 02:14 UTC, Wo-ogie approved these changes
수고하셨습니다!

2024-03-21 02:14 UTC, merged