내 프로필 사진 변경 API 구현
Ajou-Hertz/hertz-backend pull request #86
Opened 2024-03-18 12:20 UTC by tinon1004

## 🔥 Related Issue
- Close #73

## 🏃‍ Task
- AmazonS3Service: 파일 단건 삭제 기능 구현
-내 프로필 사진 변경 API 구현

## 📄 Reference
- None

2024-03-19 15:01 UTC, Wo-ogie commented
미구현된 기능이 많아 일시적으로 PR close

2024-03-21 11:47 UTC, Wo-ogie requested changes

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		@RequestParam("profileImage") MultipartFile profileImage
논의 내용) `@RequestPart`로 변경

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		value = "/me/profile-image",
```suggestion
		value = "/me/profile-images",
```

컨벤션 맞춰 복수형으로 작성해주세요~

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/dto/request/UpdateProfileImageUrlRequest.java
미사용 클래스 => 삭제 필요

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +	public UserResponse updateProfileImageUrlV1(
```suggestion
	public UserResponse updateProfileImageV1(
```

어차피 프로필 이미지 entity도 실제로 업데이트 할거라서 Url은 빼는 게 더 좋은 naming인 거 같아요.

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +	 */
```suggestion
	/**
	 * 유저의 프로필 이미지를 업데이트한다.
	 *
	 * @param userId 유저 id
	 * @param newProfileImage 새로운 프로필 이미지
	 * @return 업데이트된 유저 정보
	 */
```

혼자 튀어나와 있는 친구 ㅎㅎ 정리해주세요 :)

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/file/dto/FileDto.java
> +
논의 내용) 삭제

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/entity/User.java
> +	}
논의 내용) 삭제

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/entity/UserProfileImage.java
> +	}
논의 내용) 삭제

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +   }
변경되어야 하는 비즈니스 로직 흐름
1. 유저 entity 조회
2. 기존 프로필 이미지 DB에서 조회 (by. `userId`, `UserProfileImage`에 `User`에 unique constraints 추가)
3. 기존 프로필 이미지 DB 및 S3에서 삭제
4. 새로운 프로필 이미지 S3에 업로드
5. S3에 업로드한 파일로 `UserProfileImage` entity 생성하여 DB 저장.
6. `User` entity의 profile image url 새로운 프로필 이미지 주소로 업데이트

2024-03-21 11:47 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +   }
\+ `UserProfileImage`에 대한 service layer 구현하여 관심사 분리.

2024-03-24 02:22 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/dto/request/UpdateProfileImageUrlRequest.java
@tinon1004 반영 안됐습니다.

2024-03-24 02:24 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +			profileImage);
이 로직은 왜 갑자기 controller로 튀어나갔을까요?
기존처럼 다시 business logic에 포함시키는게 좋을 거 같아요

2024-03-24 02:24 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/common/file/dto/FileDto.java
> +
@tinon1004 반영 안됐습니다

2024-03-24 14:57 UTC, Wo-ogie requested changes

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/repository/UserProfileImageRepository.java
> +}
이거 기능구현 잘못된 거 같은데요?
user id로 where 조건 걸어서 조회하는거라면 이렇게 method naming 하시면 안됩니다.
참고 내용: https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html
```suggestion
public interface UserProfileImageRepository extends JpaRepository<UserProfileImage, Long> {
	Optional<UserProfileImage> findByUser_Id(Long userId);
}
```

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
> +	private final UserProfileImageRepository userProfileImageRepository;
안쓰는 의존성은 정리해주세요.
Import 문과 다르게 불필요한 의존성은 꼭 정리하는거 검토 부탁드립니다.

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserProfileImageCommandService.java
> +}
`UserProfileImageCommandService.updateProfileImage()`라기에는 너무 담당하는 역할이 많아요. 그렇기 때문에 메서드 코드 자체도 뚱뚱해졌고, 테스트 해야 하는 케이스도 많아졌죠.

메서드 이름은 유저 프로필 이미지 변경인데, 유저 정보 조회도 하고, 이미지 업로드도 하고, 이미지 삭제도 하고, 유저 정보 업데이트도 하고...

역할을 좀 분리해주시면 코드 가독성 및 유지보수성도 더 좋아질 거 같아요.

일단 유저를 조회하고 유저 정보를 업데이트 하는건 user service 쪽에서 담당하는게 좋을 거 같구요. User profile image service 내에서도 이미지를 저장하는 기능과 삭제하는 기능을 분리해보면 좋을 거 같네요.

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserProfileImageCommandService.java
> +		String uploadPath = "user-profile-images/";
이런 값은 user profile image 관련하여 전역적으로 사용하게 될텐데 constant value(`static final String`)로 따로 빼서 관리하는게 좋아보여요.

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +		@RequestPart("profileImage") MultipartFile profileImage
```suggestion
		@RequestPart MultipartFile profileImage
```

Request parameter로 받고자 하는 이름은 기본적으로 변수명과 같게 설정되기 때문에, 특별히 명시하시려고 하신 게 아니라면 뺴도 괜찮습니다.

2024-03-24 14:57 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +	)
받고자 하는 media type을 multipart/form-data 제한할 필요는 없지 않을까요?

```suggestion
	@PutMapping(
		value = "/me/profile-images",
		headers = API_VERSION_HEADER_NAME + "=" + 1,
	)
```

2024-03-25 04:06 UTC, tinon1004 commented on src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
> +	)
consumes = MediaType.MULTIPART_FORM_DATA_VALUE 를 사용하는게 파일 업로드에 보장된 기본적인 방법이라고 생각해서 이 방법이 가장 나을 것 같다고 생각했습니다! 혹시 생각하시는 다른 방법이 있으실까요?

2024-03-25 05:30 UTC, Wo-ogie requested changes

2024-03-25 05:30 UTC, Wo-ogie commented on src/main/java/com/ajou/hertz/domain/user/service/UserProfileImageCommandService.java
> +		UserProfileImage newUserProfileImage = uploadNewProfileImage(user, newProfileImage);
혹시 flush를 이 부분으로 옮겨주실 수 있을까요?
이유는 이따가 따로 말씀드릴게요

```suggestion
		deleteOldProfileImage(user.getId());
		userProfileImageRepository.flush();
		UserProfileImage newUserProfileImage = uploadNewProfileImage(user, newProfileImage);
```

2024-03-25 07:25 UTC, Wo-ogie requested changes

2024-03-25 07:25 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
> +
이런건 이제 굳이 테스트 안하셔도 될 거 같아요.
유저 조회 시 에러가 발생한 경우 특별한 로직이 수행되는 것도 아니고, 그냥 유저 조회 method에서 던진 exception 그대로 던져지는거니까요. 해서 나쁠 건 없지만 굳이 안해도 될 것 같아 보입니다.

2024-03-25 07:25 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserProfileImageCommandServiceTest.java
> +	private FileService fileService;
불필요한 요소들까지 mocking 되어 있는 거 같은데요?
검토 및 정리가 필요해보입니다.

2024-03-26 06:04 UTC, Wo-ogie requested changes

2024-03-26 06:04 UTC, Wo-ogie commented on src/test/java/com/ajou/hertz/unit/domain/user/service/UserProfileImageCommandServiceTest.java
> +	private HertzProperties hertzProperties;
이것도 안쓰지 않나요?

2024-03-26 06:16 UTC, Wo-ogie approved these changes

2024-03-26 06:16 UTC, merged